"""
Stage 10: Synthetic-Model Export.

Generates a Python class from a generalized template that can instantly
parse spreadsheets matching the template format into structured data.
"""

from __future__ import annotations

import logging
import textwrap
from pathlib import Path
from typing import Any

from ..models.common import CellCoord
from ..models.template import DOFType, GeneralizedTemplate, TemplateNode

logger = logging.getLogger(__name__)

# Default DOF threshold for triggering re-analysis
_DEFAULT_DOF_THRESHOLD = 50


class SpreadsheetImporter:
    """
    Base class for template-generated spreadsheet importers.

    Subclasses are generated by ModelExporter and provide:
    - validate_structure(): Check that a workbook matches the template
    - extract_data(): Extract DOF values into a structured dict
    """

    # To be set by generated subclasses
    TEMPLATE_ID: str = ""
    EXPECTED_SHEETS: list[str] = []
    CONSTANT_CELLS: dict[str, Any] = {}  # "Sheet!A1" → expected value
    DOF_CELLS: list[str] = []  # "Sheet!A1" list of DOF cell refs
    FORMULA_CELLS: list[str] = []  # "Sheet!A1" list of formula cell refs
    CONSTRAINTS: dict[str, Any] = {}  # constraint_type → value

    def validate_structure(self, workbook) -> list[str]:
        """
        Validate that a workbook matches the template structure.

        Returns:
            List of validation errors (empty if valid).
        """
        errors = []

        # Check sheet existence
        for sheet_name in self.EXPECTED_SHEETS:
            found = False
            for sheet in workbook.sheets:
                if sheet.sheet_name == sheet_name:
                    found = True
                    break
            if not found:
                errors.append(f"Missing expected sheet: {sheet_name}")

        # Check constant cells
        for ref, expected in self.CONSTANT_CELLS.items():
            parts = ref.split("!")
            if len(parts) != 2:
                continue
            sheet_name, cell_ref = parts
            sheet = workbook.get_sheet(sheet_name)
            if sheet is None:
                continue

            # Parse A1 ref
            coord = self._parse_a1(cell_ref)
            if coord is None:
                continue

            cell = sheet.get_cell(coord.row, coord.col)
            if cell is None:
                errors.append(f"Missing constant cell {ref} (expected: {expected})")
            elif str(cell.raw_value) != str(expected):
                errors.append(
                    f"Constant cell {ref}: expected '{expected}', got '{cell.raw_value}'"
                )

        return errors

    def extract_data(self, workbook) -> dict[str, Any]:
        """
        Extract DOF values from a workbook into a structured dict.

        Returns:
            Dict mapping cell references to their values.
        """
        data = {}
        for ref in self.DOF_CELLS:
            parts = ref.split("!")
            if len(parts) != 2:
                continue
            sheet_name, cell_ref = parts
            sheet = workbook.get_sheet(sheet_name)
            if sheet is None:
                continue

            coord = self._parse_a1(cell_ref)
            if coord is None:
                continue

            cell = sheet.get_cell(coord.row, coord.col)
            data[ref] = cell.raw_value if cell else None

        return data

    def check_dof_threshold(self, threshold: int = _DEFAULT_DOF_THRESHOLD) -> bool:
        """
        Check if the template has an acceptable number of DOFs.

        Returns:
            True if DOF count is within threshold, False if re-analysis needed.
        """
        return len(self.DOF_CELLS) <= threshold

    @staticmethod
    def _parse_a1(ref: str) -> CellCoord | None:
        """Parse an A1-style reference into a CellCoord."""
        col_str = ""
        row_str = ""
        for ch in ref:
            if ch.isalpha():
                col_str += ch
            elif ch.isdigit():
                row_str += ch
        if not col_str or not row_str:
            return None

        col = 0
        for ch in col_str.upper():
            col = col * 26 + (ord(ch) - ord("A") + 1)
        return CellCoord(row=int(row_str), col=col)


class ModelExporter:
    """
    Generates Python code from a GeneralizedTemplate.

    The generated module contains a SpreadsheetImporter subclass
    that can validate and extract data from matching spreadsheets.
    """

    def __init__(self, dof_threshold: int = _DEFAULT_DOF_THRESHOLD):
        self._dof_threshold = dof_threshold

    def export_code(
        self,
        template: GeneralizedTemplate,
        class_name: str = "GeneratedImporter",
    ) -> str:
        """
        Generate Python code for a SpreadsheetImporter subclass.

        Args:
            template: The generalized template to export.
            class_name: Name for the generated class.

        Returns:
            Python source code as a string.
        """
        # Collect all cells by type
        constants: dict[str, str] = {}  # ref → value
        dofs: list[str] = []
        formulas: list[str] = []
        sheets: set[str] = set()

        for node in template.template_nodes:
            sheets.add(node.sheet_name)
            for spec in node.cell_specs:
                ref = f"{node.sheet_name}!{spec.coord.to_a1()}"
                if spec.dof_type == DOFType.CONSTANT:
                    constants[ref] = repr(spec.constant_value)
                elif spec.dof_type == DOFType.DOF:
                    dofs.append(ref)
                elif spec.dof_type == DOFType.FORMULA:
                    formulas.append(ref)

        # Collect constraints
        all_constraints: dict[str, str] = {}
        for node in template.template_nodes:
            for c in node.constraints:
                key = f"{node.sheet_name}:{c.constraint_type}"
                if c.expected_value is not None:
                    all_constraints[key] = repr(c.expected_value)
                elif c.min_value is not None:
                    all_constraints[key] = f"({c.min_value!r}, {c.max_value!r})"

        # Format dicts/lists as indented code
        constants_str = self._format_dict(constants, value_is_repr=True)
        dofs_str = self._format_list(dofs)
        formulas_str = self._format_list(formulas)
        sheets_str = repr(sorted(sheets))
        constraints_str = self._format_dict(all_constraints, value_is_repr=True)

        code = textwrap.dedent(f'''\
            """
            Auto-generated spreadsheet importer.

            Generated from template: {template.template_id}
            Source files: {", ".join(template.source_files)}
            Constants: {template.total_constants} | DOFs: {template.total_dofs} | Formulas: {template.total_formulas}
            """

            from xlsx_parser.export.model_exporter import SpreadsheetImporter
            from xlsx_parser import parse_workbook


            class {class_name}(SpreadsheetImporter):
                """Importer for spreadsheets matching the detected template."""

                TEMPLATE_ID = {template.template_id!r}
                EXPECTED_SHEETS = {sheets_str}
                CONSTANT_CELLS = {constants_str}
                DOF_CELLS = {dofs_str}
                FORMULA_CELLS = {formulas_str}
                CONSTRAINTS = {constraints_str}


            def import_workbook(path: str) -> dict:
                """
                Parse and extract data from a spreadsheet matching the template.

                Args:
                    path: Path to the .xlsx file.

                Returns:
                    Dict mapping cell references to extracted values.

                Raises:
                    ValueError: If the workbook doesn't match the template.
                """
                importer = {class_name}()

                # Check DOF threshold
                if not importer.check_dof_threshold():
                    raise ValueError(
                        f"Template has too many degrees of freedom "
                        f"({{len(importer.DOF_CELLS)}}). Re-analysis recommended."
                    )

                # Parse the workbook
                result = parse_workbook(path=path)

                # Validate structure
                errors = importer.validate_structure(result.workbook)
                if errors:
                    raise ValueError(
                        f"Workbook does not match template: {{'; '.join(errors)}}"
                    )

                # Extract data
                return importer.extract_data(result.workbook)
        ''')

        logger.info(
            "Generated importer class '%s' with %d constants, %d DOFs, %d formulas",
            class_name,
            len(constants),
            len(dofs),
            len(formulas),
        )
        return code

    def export_to_file(
        self,
        template: GeneralizedTemplate,
        output_path: str | Path,
        class_name: str = "GeneratedImporter",
    ) -> Path:
        """
        Generate and write the importer code to a file.

        Returns:
            Path to the generated file.
        """
        code = self.export_code(template, class_name)
        path = Path(output_path)
        path.write_text(code)
        logger.info("Wrote generated importer to %s", path)
        return path

    @staticmethod
    def _format_dict(d: dict, value_is_repr: bool = False) -> str:
        """Format a dict as indented Python code."""
        if not d:
            return "{}"
        lines = ["{"]
        for k, v in sorted(d.items()):
            if value_is_repr:
                lines.append(f"        {k!r}: {v},")
            else:
                lines.append(f"        {k!r}: {v!r},")
        lines.append("    }")
        return "\n".join(lines)

    @staticmethod
    def _format_list(items: list[str]) -> str:
        """Format a list as indented Python code."""
        if not items:
            return "[]"
        if len(items) <= 3:
            return repr(items)
        lines = ["["]
        for item in sorted(items):
            lines.append(f"        {item!r},")
        lines.append("    ]")
        return "\n".join(lines)
